### ISSUE TITLE
Setup in Schedule links to r-novice-inflammation instead of python-novice-gapminder

### ISSUE THREAD

**Issue by tmunker** [ubvu/2023-11-14-uvavu-online#2]
On https://ubvu.github.io/2023-11-14-uvavu-online/ in the 'Schedule' section on day 1 at 9:30 the Setup links to https://swcarpentry.github.io/r-novice-inflammation/index.html instead of https://swcarpentry.github.io/python-novice-gapminder/index.html

![image](https://github.com/ubvu/2023-11-14-uvavu-online/assets/110609206/24e35ba5-4adb-4caa-bed4-2a95f1803f79)

**Comment by vansteph** [comment]
Damn! closed with pull request #4
