### ISSUE TITLE
Tables are broken on the landing page

### ISSUE THREAD

**Issue by tmunker** [ubvu/2023-11-14-uvavu-online#3]
It seems that some html code in the table of Day 3 may have been accidentally deleted, causing the Setup to be displayed instead of Day 4. 

![image](https://github.com/ubvu/2023-11-14-uvavu-online/assets/110609206/7787695a-e27f-4668-b5d6-c1792c17f70c)

**Comment by vansteph** [comment]
closed with pull request #4
